clone:
  path: github.com/drone-plugins
  recursive: true

build:
  image: armhfbuild/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=arm
    - CGO_ENABLED=0
  commands:
    - git clone --single-branch https://github.com/drone-plugins/drone-cache
    - cd drone-cache
    - sed -i 's/FROM gliderlabs\/alpine/FROM armhfbuild\/alpine/' Dockerfile
    - go get
    - go build
    - go test

publish:
  docker:
    context: drone-cache
    file: drone-cache/Dockerfile
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfplugins/drone-cache
    when:
      repo: armhf-drone-plugins/drone-cache
      branch: master

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/cac16e3f9e62a24bcd78

  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
